# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build-and-test:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run tests on package
          command: |
            . venv/bin/activate
            python -m pytest

      - run:
          name: Push to PyPi (if is tag)
          command: |
            . venv/bin/activate
            .circleci/twine_upload.sh

deployment:
  tag_build_for_cci2:
    # 1.0 style config for tag builds workaround
    # For context, see:
    # - https://discuss.circleci.com/t/build-on-tag/9864/30
    # - https://discuss.circleci.com/t/git-tag-deploys-in-2-0/9493/8
    # - https://circleci.com/gh/keybits/circulate/58#config/containers/0
    tag: /release-([0-9]+)\.([0-9]+)\.([0-9]+)/
    commands:
      - true
